# Generated by Django 5.1.7 on 2025-04-14 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('RUN', 'Running'), ('SWIM', 'Swimming'), ('BIKE', 'Cycling'), ('GYM', 'Gym Workout'), ('WLK', 'Walking'), ('HIIT', 'HIIT'), ('YOGA', 'Yoga')], max_length=4)),
                ('duration', models.FloatField(help_text='Duration in minutes')),
                ('distance', models.FloatField(blank=True, help_text='Distance in kilometers', null=True)),
                ('calories_burned', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
